openapi: 3.0.0
info:
  title: Word Redaction API
  description: Mask sensitive content within your documents
  version: 0.1.9
servers:
  - url: https://glasswallredact.azurewebsites.net
    description: Azure
paths:
  /api/RedactFile:
    post:
      summary: Returns a document with redactions.
      description: Returns a document with sensitive content redacted with the chosen character.
      parameters:
        - name: x-api-key
          in: header
          description: "API Key purchased from https://glasswall-store.com/"
          schema:
            type: string
          required: true
      requestBody:
        content:
          "multipart/form-data":
            schema:
              required: file, redactJson
              type: object
              properties:
                file:
                  type: string
                  format: binary
                redactJson:
                  type: string
            encoding:
              file:
                style: form
      responses:
        "200": # status code
          description: Success
        "400":
          description: Bad Request
